import React from 'react';
import { fetchPublicOrder } from '@/app/actions/public'; 
import InvoiceA4 from '@/app/components/InvoiceA4'; 
import PrintButton from '@/app/components/PrintButton'; // Use your existing print button
import { notFound } from 'next/navigation';

export default async function PublicBillPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  // 1. Use the PUBLIC action (doesn't check for staff login)
  const order = await fetchPublicOrder(id);

  if (!order) {
    return notFound(); // Shows a 404 page if bill doesn't exist
  }

  return (
    <main className="min-h-screen bg-slate-100 flex flex-col items-center py-10 px-4">
      
      {/* Action Bar */}
      <div className="w-full max-w-[210mm] flex justify-between items-center mb-6 print:hidden">
        <h1 className="text-xl font-bold text-slate-800">
          Invoice View
        </h1>
        <PrintButton />
      </div>

      {/* The Actual Invoice (A4 Size) */}
      <div className="shadow-2xl print:shadow-none">
         <InvoiceA4 
           order={order} 
           branch={order.branch_data} // fetchPublicOrder returns branch details in this key
         />
      </div>

      {/* Mobile Hint */}
      <p className="mt-6 text-xs text-slate-400 print:hidden">
        Generated by Nath Drycleaners System
      </p>
    </main>
  );
}